[package]
name = "rp2040-hal"
version = "0.1.0"
authors = ["evan <evanmolder@gmail.com>"]
edition = "2018"
homepage = "https://github.com/rp-rs/rp-hal/boards/pico-bsc"
description = "A Rust Embeded-HAL impl for the rp2040 microcontroller"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.1"
embedded-hal = "0.2.4"
nb = "1.0.0"
rp2040-pac = "0.1.1"
vcell = "0.1"
pio = { git = "https://github.com/rp-rs/pio-rs.git", branch = "main" }
